#!/usr/bin/env bash
# A modified version of Dylan Araps' script (https://github.com/dylanaraps/bin/blob/master/wal-set)
{% do require('notification_daemon', 'status_bar') %}

# Import the colors generated by wal.
source "${HOME}/.cache/wal/colors.sh"

{% if notification_daemon == 'dunst' %}
# Restart and re-theme the notification system.
killall -9 dunst
dunst \
    -bf "$foreground" \
    -cb "$color4" \
    -cf "$foreground" \
    -cfr "$color4" \
    -cto 10 \
    -lb "$color3" \
    -lf "$foreground" \
    -lfr "$color3" \
    -lto 1 \
    -nb "$color3" \
    -nf "$foreground" \
    -nfr "$color3" \
    -nto 3 \
    -font "$UI_FONT" \
    -frame_color "$color3" \
    -geometry "${DUNST_SIZE:-300x30-40+40}" \
    -separator_color "$color3" &
{% endif %}

{% if status_bar == 'polybar' %}
# Restart and re-theme polybar.
$HOME/.config/scripts/polybar-start.sh
{% endif %}
