# ~/.config/x/.xinitrc
# My primary X configuration file

# Setup emacs as my editor
export EDITOR='emacs'

# Set various font variables for theming
export UI_FONT='curie 12'

# Boring language stuff
export LANG='en_US.UTF-8'
export LC_CTYPE='en_US.UTF-8'

# Setup dunst
export DUNST_FONT='pango:curie 12'
export DUNST_SIZE='300x30-40+40'

# Additional x settings
xset s off -dpms
xset m 1/1
xset -b

# Merge in the Xresources
xrdb -merge "$HOME/.Xresources"

# Setup the urxvt daemon
urxvtd -q -f &

# Restore the previous colorscheme without setting the wallpaper
wal -R -n

# Start i3
exec i3
