#!/bin/bash
# ~/.config/scripts/i3-exec-tiling
# Script to launch windows in tiling window mode
# Usage: i3-exec-tiling application workspace

# Set the maximum number of seconds we are willing to wait
maxwait=12
currentwait=0

# First. we launch the application
echo "Launching $1..."
$1 &

# Now we wait until we see the window for the application appear, moving it to the desired workspace
until [ "$currentwait" -eq "$maxwait" ]; do
    # Get the list of pid's
    pids=$(wmctrl -l -p | cut -d ' ' -f 4)

    # Iterate through the pids determine if they have the same "comm" as what we passed
    while read -r p; do
        pcomm=$(cat "/proc/$p/comm" | tr '[:upper:]' '[:lower:]')
        if echo "$1" | grep -i -q "$pcomm"; then
            echo "Found process at pid $p"
            # Focus the window
            wmctrl -i -a "$(wmctrl -l -p | grep $p | cut -d ' ' -f 1)"
            # Disable floating mode (tile it)
            i3-msg floating disable
            # Move the window the specified workspace
            i3-msg move container to workspace $2
            exit
        fi
    done <<< "$pids"
    
    # Increment the wait time
    let "currentwait+=1"
    sleep 1
done

echo "Unable to find process!"
exit 1
