#!/bin/bash
# ~/.config/scripts/logoff-wrapper
# Wrapper script for logging off of i3

# Kill polybar and dunst
killall -9 polybar
killall -9 dunst

# Kill common stuff
killall -9 atom
killall -9 firefox
killall -9 keepassx2
killall -9 mathematica
killall -9 pidgin
killall -9 thunderbird
killall -9 urxvtd

# Exit i3
i3-msg exit
