#!/bin/bash
# ~/.config/scripts/i3-startup
# Script to ensure that certain initialization sub-scripts don't get into a race-condition

# Setup monitor configuration
$HOME/.config/scripts/setup-monitors

# Re-launch pywal, this time allowing it to set the background, and execute wal-set afterwards
wal -R -o "$HOME/.config/scripts/wal-set"

# Send a welcome message
sleep 3
notify-send -u normal 'i3' 'Initialization complete. Hello, Harrison :)' &

