#!/bin/bash
# ~/.config/scripts/rofi-exit
# Utilizes rofi's script mode when exiting i3

options="Cancel|Logout|Restart|Shutdown"
prompt="What would you like to do?"

result=$(echo "$options" | rofi -sep "|" -dmenu -font "${font:-Artwiz Lemon 7}" -bw 3 -hide-scrollbar -i -only-match -l 4 -p "$prompt")

if [ $result == "Cancel" ]; then
    exit 0
elif [ $result == "Logout" ]; then
    i3-msg exit
elif [ $result == "Restart" ]; then
    systemctl reboot
elif [ $result == "Shutdown" ]; then
    systemctl poweroff
else
    echo "Unknown option."
    exit 1
fi
