#!/bin/bash
# ~/.config/scripts/rofi-exit
# Utilizes rofi's script mode when exiting i3

result=$(echo "Yes|No" | rofi -sep "|" -dmenu -font "${font:-Artwiz Lemon 7}" -bw 3 -hide-scrollbar -i -only-match -l 2 -p "Are you sure you want to exit i3?")

if [ $result == "Yes" ]; then
    $HOME/.config/scripts/i3-shutdown-wrapper >/dev/null 2>&1
else
    exit 0
fi
