#!/bin/bash
# ~/.config/scripts/yesno-wrapper
# The wrapper script to display yes/no to rofi

if [[ -z "$@" ]]; then
	echo Yes
	echo No
fi

if [ $# -gt 0 ]; then
    if [ $1 -eq "Yes" ]; then
        $2
    else
        $3
    fi
fi
