#!/bin/bash
# ~/.config/scripts/rofi-exit-wrapper
# The wrapper script that actually calls the i3-shutdown-wrapper

if [[ -z "$@" ]]; then
	echo Yes
	echo No
fi

if [ $# -gt 0 ]; then
    if [ $1 == "Yes" ]; then
        $HOME/.config/scripts/i3-shutdown-wrapper >/dev/null 2>&1
    else
        exit 0
    fi
fi
