#!/bin/bash
# ~/.config/scripts/setup-monitors
# A script to appropriately configure xrandr at boot

current_display_count=$(xrandr | grep connected | grep -v disconnected | wc -l)
docked_configuration='xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 1680x150 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP-1-4 --off --output DP-1-3 --mode 1680x1050 --pos 3280x0 --rotate normal --output DP2 --mode 1680x1050 --pos 0x0 --rotate normal'
undocked_configuration='xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 1680x150 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP-1-4 --off --output DP-1-3 --off --output DP2 --off'

if [ $current_display_count -gt 1 ]; then
	$docked_configuration
else
	$undocked_configuration
fi
