#!/bin/bash
# ~/.config/scripts/setup-monitors
# A script to appropriately configure xrandr at boot

display_count=$(xrandr -q | grep ' connected' | wc -l)
docked='xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 1680x150 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP-1-4 --off --output DP-1-3 --mode 1680x1050 --pos 3280x0 --rotate normal --output DP2 --mode 1680x1050 --pos 0x0 --rotate normal'
undocked='xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 1680x150 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP-1-4 --off --output DP-1-3 --off --output DP2 --off'
one_monitor_left='xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 1440x256 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --mode 1440x900 --pos 0x0 --rotate normal --output DP-1-4 --off --output DP-1-3 --off --output DP2 --off'

if [ $display_count -eq 3 ]; then
    $docked
elif [ $display_count -eq 2 ]; then
    $one_monitor_left
else
    $undocked
fi
