#!/bin/bash
# ~/.config/polybar/network-status-detailed
# Script for displaying (detailed) network status as a polybar module

if ip -4 addr | grep -q 'state UP'; then
    ACTIVE_NET_PROFILE=$(netctl list | grep '*' | cut -d ' ' -f 2)
    ACTIVE_INTERFACE=$(ip -4 addr | grep 'state UP' | cut -d ' ' -f 2 | tr -d ':')
    ACTIVE_MAC=$(cat /sys/class/net/$ACTIVE_INTERFACE/address)
    ACTIVE_IP=$(ip -4 addr | grep 'state UP' -A 1 | tail -n 1 | cut -d ' ' -f 6 | cut -d '/' -f 1)
    notify-send -u low "NET" "$ACTIVE_NET_PROFILE ($ACTIVE_INTERFACE) > $ACTIVE_MAC > $ACTIVE_IP" -t 10000
else
    notify-send -u low "NET" "DOWN" -t 1000
fi
