#!/bin/bash
# ~/.config/polybar/vpn-status-detailed
# Script for displaying (detailed) vpn status as a polybar module

if pgrep -x openvpn; then
    notify-send -u low "VPN" "UP" -t 10000
else
    notify-send -u low "VPN" "DOWN"
fi
