# ~/.config/zsh/.zshrc
# This file loads the zsh environment configuration files
#
# To make this work, you'll need to create a symlink between this file and another ".zshrc" in your home directory:
# ln -s ~/.config/zsh/zshrc ~/.zshrc


# Automatically start the window manager at login
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
	exec startx > $HOME/.i3-last-run.log 2>&1
fi


# Import the rest of the zsh configuration files
for f in $HOME/.config/zsh/*.zsh; do
	. $f
done
